# fly.toml app configuration file generated for discount-conpon-dev on 2023-12-14T11:09:36+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "discount-conpon-dev"
primary_region = "hkg"

[build]

[env]
  PORT = "3000"
  SCOPES = "write_products,read_price_rules,write_price_rules"
  SHOPIFY_API_KEY = "bd5542982f50074b1c0483c0012ea633"
  SHOPIFY_APP_URL = "https://discount-conpon-dev.fly.dev"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
