# fly.toml app configuration file generated for discount-coupon on 2023-11-15T11:54:08+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "discount-coupon"
primary_region = "hkg"

[build]

[env]
  PORT = "3000"
  SCOPES = "write_products,read_price_rules,write_price_rules"
  SHOPIFY_API_KEY = "430caf72a8563b14feacbc61e0742aab"
  SHOPIFY_APP_URL = "https://discount-coupon.fly.dev"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
