# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Discount Coupon"
client_id = "0093f16cfc78d5e2e91cd08f2aaa63d0"
application_url = "https://terrorists-urban-south-divine.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_price_rules,write_price_rules"

[auth]
redirect_urls = [
  "https://terrorists-urban-south-divine.trycloudflare.com/auth/callback",
  "https://terrorists-urban-south-divine.trycloudflare.com/auth/shopify/callback",
  "https://terrorists-urban-south-divine.trycloudflare.com/api/auth/callback",
  "https://terrorists-urban-south-divine.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "revashopdev.myshopify.com"
