# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Discount Coupon"
client_id = "430caf72a8563b14feacbc61e0742aab"
application_url = "https://cooler-simulation-painted-dm.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_price_rules,write_price_rules"

[auth]
redirect_urls = [
  "https://cooler-simulation-painted-dm.trycloudflare.com/auth/callback",
  "https://cooler-simulation-painted-dm.trycloudflare.com/auth/shopify/callback",
  "https://cooler-simulation-painted-dm.trycloudflare.com/api/auth/callback",
  "https://cooler-simulation-painted-dm.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "revashopdev.myshopify.com"
